name: main

on:
  push:
    branches: [main, test-me-*]
    tags: '*'
  pull_request:

jobs:
  main-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: asottile/workflows/.github/actions/fast-checkout@v1.5.0
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/setup-go@v3
    - run: |
        pip install --upgrade setuptools wheel
        pip wheel --no-deps --wheel-dir wheels .
  main-macos:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.5.0
    with:
      env: '["py38"]'
      os: macos-latest
      wheel-tags: true
  main-linux:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.5.0
    with:
      env: '["py38", "py39", "py310"]'
      os: ubuntu-latest
  main-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
    - run: go get -v -t -d ./...
    - run: go test .
